import initialState from './data/initial-state.json' with { type: 'json' };
import welfareData from './data/welfare-ids.json' with { type: 'json' };
const CONFIG=window.CHALDEA_CONFIG||{};
const PLAYERS=['julien','yanis','attmann'];
const PLAYER_LABELS={julien:'Julien',yanis:'Yanis',attmann:'Attmann'};
const CLASS_ORDER=['Saber','Archer','Lancer','Rider','Caster','Assassin','Berserker','Ruler','Avenger','Alter Ego','Moon Cancer','Foreigner','Pretender','Shielder','Beast'];
const MASH_IDS=new Set([1]);
const NON_VISIBLE_CLASSES=new Set(['Extra']);
const FUTURE_NAMES=new Set(['Phantasmoon','Louhi','Van Gogh (Miner)','Tutankhamun','Kazuradrop']);
const FANDOM={
 Saber:'Class-Saber-Gold.webp',Archer:'Class-Archer-Gold.webp',Lancer:'Class-Lancer-Gold.webp',Rider:'Class-Rider-Gold.webp',Caster:'Class-Caster-Gold.webp',Assassin:'Class-Assassin-Gold.webp',Berserker:'Class-Berserker-Gold.webp',Ruler:'Class-Ruler-Gold.webp',Avenger:'Class-Avenger-Gold.webp','Alter Ego':'Class-Alterego-Gold.webp','Moon Cancer':'Class-MoonCancer-Gold.webp',Foreigner:'Class-Foreigner-Gold.webp',Pretender:'Class-Pretender-Gold.webp',Shielder:'Class-Shielder-Gold.webp',Beast:'Class-Beast-Gold.webp',
 grail:'Icongrail.png', Q:'Quickmini.png', A:'Artsmini.png', B:'Bustermini.png'
};
const FANDOM_URL='https://fategrandorder.fandom.com/wiki/Special:Redirect/file/';
const state=structuredClone(initialState);
// Hide future Excel placeholders immediately; authoritative NA sync runs afterwards.
state.roster=(state.roster||[]).filter(r=>!FUTURE_NAMES.has(norm(r.name)));
let currentPlayer='julien',currentView='overview',rosterMode='cards',sortDir='desc',compareFocusId=2;
let cloud=null,session=null,currentAuth=null,cloudEnabled=false,atlasById=new Map(),atlasFull=new Map(),renderToken=0, supportPlayer='julien';
const selectedClasses=new Set(),selectedRarities=new Set();
const supportLocal={julien:{friendId:'939739133'},yanis:{friendId:''},attmann:{friendId:''}};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const num=v=>{if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null};
const norm=s=>String(s||'').normalize('NFD').replace(/[̀-ͯ]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const toast=m=>{const e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2000)};
const WELFARE_NAMES=new Set((welfareData.names||[]).map(norm));
const WELFARE_IDS=new Set((welfareData.ids||[]).map(Number));
const localKey='chaldea-v5-cache';
function rarityNum(r){return r==='SSR'?5:r==='SR'?4:r==='R'?3:r==='UC'?2:1}
function classKey(c){const s=String(c||'').replace(/\n/g,' ').trim();return s==='Moon'?'Moon Cancer':s}
function fandomAsset(name){return FANDOM_URL+encodeURIComponent(name)}
function classImg(c){const k=classKey(c);const f=FANDOM[k]||FANDOM.Saber;const fallback=`Class-${k.replace(/ /g,'')}-Gold.png`;return `<img class="class-icon-img" src="${fandomAsset(f)}" alt="${k}" loading="eager" onerror="if(this.dataset.fb){this.style.display='none'}else{this.dataset.fb='1';this.src='${fandomAsset(fallback)}'}">`}
function cardImg(t){return `<img src="${fandomAsset(FANDOM[t])}" alt="${t}" loading="eager">`}
function grailImg(){return `<img class="grail-thumb" src="${fandomAsset(FANDOM.grail)}" alt="Graal" loading="eager" onerror="this.style.display='none'">`}
function isWelfare(r){return WELFARE_IDS.has(Number(r.id))||r.rarity==='Welfare'||WELFARE_NAMES.has(norm(r.name))}
function isCounted(r){return !MASH_IDS.has(Number(r.id))&&!r.nonCounted&&!NON_VISIBLE_CLASSES.has(classKey(r.class))}
function isVisible(r){return !NON_VISIBLE_CLASSES.has(classKey(r.class))&&!FUTURE_NAMES.has(norm(r.name))}
function stats(p,id){return state.players[p]?.stats?.[String(id)]||{level:null,np:null,bond:null,grail:null,fouHp:null,fouAtk:null,servantCoins:null,skills:[null,null,null],appendSkills:[null,null,null,null,null]}}
function ensureStats(p,id){state.players[p]??={displayName:PLAYER_LABELS[p],stats:{}};state.players[p].stats??={};state.players[p].stats[String(id)]??={level:null,np:null,bond:null,grail:null,fouHp:null,fouAtk:null,servantCoins:null,skills:[null,null,null],appendSkills:[null,null,null,null,null]};return state.players[p].stats[String(id)]}
function isOwned(p,r){if(!isCounted(r))return true;const s=stats(p,r.id);return ['level','np','bond','grail','fouHp','fouAtk','servantCoins'].some(k=>s[k]!=null)||[...(s.skills||[]),...(s.appendSkills||[])].some(v=>v!=null)}
function validSkill(v){return Number.isFinite(v)&&v>=1&&v<=10}
function values(p,idx=null){const a=[];for(const r of state.roster){if(!isCounted(r))continue;const s=stats(p,r.id);const vals=idx===null?(s.skills||[]):[s.skills?.[idx]];for(const v of vals)if(validSkill(v))a.push(Number(v))}return a}
function average(p,idx=null){const a=values(p,idx);return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}
function skillDist(p){const d=Array(11).fill(0);values(p).forEach(v=>d[v]++);return d}
function countOwned(p,pred=()=>true){return state.roster.filter(r=>isVisible(r)&&pred(r)&&isOwned(p,r)).length}
function countLevel(p,level){return countOwned(p,r=>Number(stats(p,r.id).level)===level)}
function bond10(p){return countOwned(p,r=>Number(stats(p,r.id).bond)>=10)}
function fourFiveUniverse(){return state.roster.filter(r=>isCounted(r)&&(rarityNum(r.rarity)>=4))}
function fourFiveOwned(p){return fourFiveUniverse().filter(r=>isOwned(p,r)).length}
function collectionPct(p){const den=fourFiveUniverse().length;return den?fourFiveOwned(p)/den*100:0}
function coinEstimate(r,s){if(rarityNum(r.rarity)<4||!isOwned(currentPlayer,r))return null;if(s.servantCoins!=null)return{value:s.servantCoins,estimated:false};let n=Math.max(1,Number(s.np)||1),base=rarityNum(r.rarity)===5?90:50;let copy=Math.max(0,n-1)*base;let bond=Math.max(0,Number(s.bond)||0);let bondCoins=[0,0,0,0,0,30,45,60,75,90,105][Math.min(10,bond)]||0;let app=(s.appendSkills||[]).filter(validSkill).length*20;return{value:copy+base+bondCoins+app,estimated:true}}
function clampNP(s){return s.np==null?'—':Math.min(5,Math.max(0,Number(s.np)))}
function updateSync(text,error=false){$('#syncText').textContent=text;$('#syncDot').parentElement.classList.toggle('error',error)}
function currentCanEdit(){return !!currentAuth?.canEdit&&currentAuth.playerKey===currentPlayer}
function renderMasterSwitch(){
 $('#masterSwitch').innerHTML=PLAYERS.map(p=>`<button class="master-tab ${p===currentPlayer?'active':''}" data-player="${p}">${state.players[p]?.displayName||PLAYER_LABELS[p]}</button>`).join('');
 $$('.master-tab').forEach(b=>b.onclick=()=>{currentPlayer=b.dataset.player;supportPlayer=currentPlayer;renderAll()});
 $('#heroMaster').textContent=state.players[currentPlayer]?.displayName||PLAYER_LABELS[currentPlayer];
 $('#accountText').textContent=session?(currentAuth?.canEdit?`Connecté · ${PLAYER_LABELS[currentAuth.playerKey]}`:'Connecté · lecteur'):'Connexion';
}
function renderOverview(){
 const p=currentPlayer, owned=countOwned(p),five=countOwned(p,r=>rarityNum(r.rarity)===5&&!isWelfare(r)),four=countOwned(p,r=>rarityNum(r.rarity)===4&&!isWelfare(r)),wf=countOwned(p,r=>isWelfare(r));
 $('#introOwned').textContent=owned;
 $('#rarityDisplay').innerHTML=`<div class="rarity-card"><span class="label">5 STAR</span><span class="stars">★★★★★</span><span class="value">${five}</span></div><div class="rarity-card"><span class="label">4 STAR</span><span class="stars">★★★★</span><span class="value">${four}</span></div><div class="rarity-card welfare"><span class="label">WELFARE</span><span class="stars">FREE</span><span class="value">${wf}</span></div>`;
 const dist=skillDist(p),mx=Math.max(...dist.slice(1),1);$('#skillsAverage').textContent=average(p).toFixed(1);$('#skillBars').innerHTML=Array.from({length:10},(_,i)=>10-i).map(l=>`<div class="skill-row"><span class="skill-level">${l}</span><div class="skill-track"><div class="skill-fill" style="width:${dist[l]/mx*100}%"></div></div><b>${dist[l]}</b></div>`).join('');
 const markers=[['MOYENNE SKILL 1',average(p,0).toFixed(1)],['MOYENNE SKILL 2',average(p,1).toFixed(1)],['MOYENNE SKILL 3',average(p,2).toFixed(1)],['BOND 10+',bond10(p)],['NIVEAU 120',countLevel(p,120)],['MOYENNE NP',(()=>{const a=state.roster.filter(r=>isVisible(r)&&isOwned(p,r)).map(r=>Number(stats(p,r.id).np)).filter(Number.isFinite);return a.length?(a.reduce((x,y)=>x+y,0)/a.length).toFixed(1):'—'})()]];
 $('#detailStats').innerHTML=markers.map(([l,v])=>`<div class="marker"><small>${l}</small><strong>${v}</strong></div>`).join('');
 const pct=collectionPct(p),pctStr=pct.toFixed(1).replace('.0','');$('#collectionPct').textContent=pctStr+'%';$('#collectionRing').style.background=`conic-gradient(#5f89bc 0 ${pct}%,#edf1f5 ${pct}% 100%)`;
 const bars=[['5★',five],['4★',four],['Welfare',wf]],m=Math.max(...bars.map(x=>x[1]),1);$('#miniBars').innerHTML=bars.map(([l,v])=>`<div class="mini-bar"><span>${l}</span><div class="mini-track"><div class="mini-fill" style="width:${v/m*100}%"></div></div><b>${v}</b></div>`).join('');
}
function fillFilters(){
 const classes=[...new Set(state.roster.filter(isVisible).map(r=>classKey(r.class)).filter(Boolean))].sort((a,b)=>CLASS_ORDER.indexOf(a)-CLASS_ORDER.indexOf(b));
 $('#classPop').innerHTML=classes.map(c=>`<label class="check-item"><input type="checkbox" data-class="${c}" ${selectedClasses.has(c)?'checked':''}>${classImg(c)}<span>${c}</span></label>`).join('');
 const rs=[['5','5★'],['4','4★'],['3','3★'],['2','2★'],['1','1★'],['welfare','Welfare']];$('#rarityPop').innerHTML=rs.map(([v,l])=>`<label class="check-item"><input type="checkbox" data-rarity="${v}" ${selectedRarities.has(v)?'checked':''}><span>${l}</span></label>`).join('');
 $$('#classPop input').forEach(i=>i.onchange=()=>{i.checked?selectedClasses.add(i.dataset.class):selectedClasses.delete(i.dataset.class);updateFilterLabels();renderRoster()});
 $$('#rarityPop input').forEach(i=>i.onchange=()=>{i.checked?selectedRarities.add(i.dataset.rarity):selectedRarities.delete(i.dataset.rarity);updateFilterLabels();renderRoster()});
 updateFilterLabels();
}
function updateFilterLabels(){$('#classFilterCount').textContent=selectedClasses.size?`(${selectedClasses.size})`:'';$('#rarityFilterCount').textContent=selectedRarities.size?`(${selectedRarities.size})`:''}
function sortRows(rows){const mode=$('#sortFilter').value,sg=sortDir==='asc'?1:-1;rows.sort((a,b)=>{let x=0,y=0;if(mode==='bond'){x=Number(a.s.bond)||-1;y=Number(b.s.bond)||-1}else if(mode==='np'){x=Number(a.s.np)||-1;y=Number(b.s.np)||-1}else if(mode==='level'){x=Number(a.s.level)||-1;y=Number(b.s.level)||-1}else if(mode==='rarity-level'){x=rarityNum(a.r.rarity)*1000+(Number(a.s.level)||0);y=rarityNum(b.r.rarity)*1000+(Number(b.s.level)||0)}else{x=Number(a.r.releaseNo??a.r.id);y=Number(b.r.releaseNo??b.r.id)}return(x-y)*sg});return rows}
function focusValue(r,s){const mode=$('#sortFilter').value;if(mode==='bond')return `<div class="sort-focus">Bond ${s.bond??'—'}</div>`;if(mode==='np')return `<div class="sort-focus">NP ${clampNP(s)}</div>`;if(mode==='level'||mode==='rarity-level')return `<div class="sort-focus">Lv ${s.level??'—'}</div>`;return ''}
function renderRoster(){
 const token=++renderToken,q=norm($('#searchInput').value);let rows=state.roster.filter(isVisible).map(r=>({r,s:stats(currentPlayer,r.id)})).filter(o=>{const c=classKey(o.r.class),rr=isWelfare(o.r)?'welfare':String(rarityNum(o.r.rarity));return(!q||norm(o.r.name).includes(q))&&(!selectedClasses.size||selectedClasses.has(c))&&(!selectedRarities.size||selectedRarities.has(rr))});sortRows(rows);
 $('#rosterCount').textContent=rows.length;$('#rosterSummary').textContent=`${countOwned(currentPlayer)} possédés · ${state.roster.filter(isVisible).length-countOwned(currentPlayer)} manquants`;
 $('#rosterCards').classList.toggle('hidden',rosterMode!=='cards');$('#rosterTable').classList.toggle('hidden',rosterMode!=='table');
 if(rosterMode==='cards'){
   $('#rosterCards').innerHTML=rows.map(({r,s})=>{const own=isOwned(currentPlayer,r),g=Number(s.grail)||0;return `<article class="servant-card ${own?'owned':'missing'}" data-servant-id="${r.id}">${own?'':'<span class="missing-ribbon">NON POSSÉDÉ</span>'}<div class="card-art" data-servant-id="${r.id}"><div class="loader">ATLAS</div></div><div class="card-content"><div class="card-topline"><span class="rarity-short">${rarityNum(r.rarity)}★${isWelfare(r)?' · W':''}</span>${classImg(r.class)}</div><div class="card-name">${r.name}</div><div class="card-line"><span class="level-major">Lv ${s.level??'—'} ${g?`<span class="level-sub">${grailImg()} ${g}</span>`:''}</span><span class="np-chip">NP ${clampNP(s)}</span></div>${focusValue(r,s)}</div></article>`}).join('');loadCardImages(rows,token);
 }else{$('#rosterTable').innerHTML=`<table class="table"><thead><tr><th>Servant</th><th>Classe</th><th>Rareté</th><th>Lv</th><th>NP</th><th>S1</th><th>S2</th><th>S3</th><th>Bond</th><th>Coins</th></tr></thead><tbody>${rows.map(({r,s})=>`<tr data-servant-id="${r.id}" class="${isOwned(currentPlayer,r)?'':'missing-row'}"><td><b>${r.name}</b></td><td>${classImg(r.class)}</td><td class="stars">${rarityNum(r.rarity)}★${isWelfare(r)?' · W':''}</td><td>${s.level??'—'}</td><td>${s.np??'—'}</td><td>${s.skills?.[0]??'—'}</td><td>${s.skills?.[1]??'—'}</td><td>${s.skills?.[2]??'—'}</td><td>${s.bond??'—'}</td><td>${coinEstimate(r,s)?.value??'—'}</td></tr>`).join('')}</tbody></table>`}
 $$('.servant-card,.table tr[data-servant-id]').forEach(el=>el.onclick=()=>openServant(Number(el.dataset.servantId)));
}
async function loadCardImages(rows,token){let i=0;const workers=Array.from({length:12},async()=>{while(i<rows.length){const row=rows[i++];if(token!==renderToken)return;const holder=$(`.card-art[data-servant-id="${row.r.id}"]`);if(!holder)continue;const d=await atlasDetail(row.r);let url=imageList(d)[0];if(!url){const a=atlasById.get(Number(row.r.id));url=guessImage(a?.id||row.r.atlasId)};if(url){const img=new Image();img.onload=()=>{if(token!==renderToken)return;holder.innerHTML='';holder.appendChild(img)};img.onerror=()=>{holder.innerHTML='<div class="image-fallback">ART<br><small>indisponible</small></div>'};img.src=url}}});await Promise.all(workers)}
function guessImage(atlasId){if(!atlasId)return'';const id=String(atlasId);return `https://static.atlasacademy.io/NA/CharaGraph/${id}/${id}a@1.png`}
async function fetchAtlasList(){try{const r=await fetch('https://api.atlasacademy.io/basic/NA/servant/search',{cache:'no-store'});if(!r.ok)throw Error(r.status);const arr=await r.json();return Array.isArray(arr)?arr:[]}catch{return[]}}
async function syncRosterNA(){const arr=await fetchAtlasList();if(!arr.length){$('#atlasStatus').textContent='ATLAS / NA · indisponible';return}const byColl=new Map(arr.map(x=>[Number(x.collectionNo),x]));const keep=[];for(const r of state.roster){const a=byColl.get(Number(r.id));if(a&&classKey(normalizeClass(a.className))!=='Extra'&&!FUTURE_NAMES.has(norm(a.name)))keep.push({...r,name:a.name,class:normalizeClass(a.className),rarity:atlasRarity(a),atlasId:a.id});else if(Number(r.id)===1){} }
 const seen=new Set(keep.map(r=>Number(r.id)));for(const a of arr){const id=Number(a.collectionNo);if(id<=1)continue;const name=String(a.name||'');const cls=normalizeClass(a.className);if(cls==='Extra'||FUTURE_NAMES.has(norm(name)))continue;if(!seen.has(id)){keep.push({id,name,class:cls,rarity:atlasRarity(a),attribute:a.attribute||'',cardType:a.cardType||'',atlasId:a.id});PLAYERS.forEach(p=>ensureStats(p,id));}}
 for(const r of keep){const a=byColl.get(Number(r.id));if(a){r.name=a.name;r.class=normalizeClass(a.className);r.rarity=atlasRarity(a);r.atlasId=a.id}}
 state.roster=keep.sort((a,b)=>Number(a.id)-Number(b.id));for(const r of state.roster)ensureStats('julien',r.id),ensureStats('yanis',r.id),ensureStats('attmann',r.id);
 fillFilters();renderAll();$('#atlasStatus').textContent=`ATLAS / NA · ${state.roster.filter(isCounted).length} Servants`;
}
function normalizeClass(c){const s=String(c||'').toLowerCase().replace(/[^a-z]/g,'');const m={saber:'Saber',archer:'Archer',lancer:'Lancer',rider:'Rider',caster:'Caster',assassin:'Assassin',berserker:'Berserker',ruler:'Ruler',avenger:'Avenger',alterego:'Alter Ego',mooncancer:'Moon Cancer',foreigner:'Foreigner',pretender:'Pretender',shielder:'Shielder',beast:'Beast'};return m[s]||'Extra'}
function atlasRarity(x){return Number(x.rarity)>=5?'SSR':Number(x.rarity)===4?'SR':Number(x.rarity)===3?'R':Number(x.rarity)===2?'UC':'C'}
async function atlasDetail(r){const key=Number(r.id);if(atlasFull.has(key))return atlasFull.get(key);const p=(async()=>{try{const res=await fetch(`https://api.atlasacademy.io/nice/NA/servant/${key}`,{cache:'force-cache'});if(!res.ok)throw Error();return await res.json()}catch{return null}})();atlasFull.set(key,p);return p}
function imageList(d){if(!d?.extraAssets)return[];const out=[];const add=v=>{if(typeof v==='string'&&/^https?:\/\//.test(v)&&/\.(png|jpg|jpeg|webp)(\?.*)?$/i.test(v))out.push(v)};for(const section of ['ascension','costume']){for(const branch of ['charaGraph','charaFigure','narrowFigure']){const obj=d.extraAssets?.[branch]?.[section];if(obj)Object.values(obj).forEach(add)}}return [...new Set(out)]}
function genderFix(r,d){return r.name==='Kishinami Hakuno (Female)'?'female':(d?.gender||'')}
function commandCards(d,r){const arr=(d?.cards||[]).map(x=>String(x));if(arr.length>=5)return arr.slice(0,5).map(x=>x==='1'?'A':x==='2'?'Q':x==='3'?'B':x);const map={buster:['B','B','B','A','Q'],arts:['A','A','A','B','Q'],quick:['Q','Q','Q','A','B']};return map[String(r.cardType||'buster').toLowerCase()]||map.buster}
function levelIndex(detail,level){const growth=detail?.limits?.slice?.().sort((a,b)=>a.lvMax-b.lvMax)||[];let exact=growth.find(x=>Number(x.lvMax)>=level);return exact||growth[growth.length-1]}
function statAt(detail,kind,level){if(!detail)return null;const arr=detail?.[kind+'Growth'];if(Array.isArray(arr)&&arr.length){const i=Math.max(0,Math.min(arr.length-1,level-1));return Number(arr[i])}const base=Number(detail?.[kind+'Base']),max=Number(detail?.[kind+'Max']),lvMax=Number(detail?.lvMax)||100;if(!Number.isFinite(base)||!Number.isFinite(max))return null;const t=Math.max(0,Math.min(1,(level-1)/(lvMax-1)));return Math.round(base+(max-base)*t)}
function currentStats(detail,r,s){const lvl=Math.max(1,Math.min(120,Number(s.level)||Number(detail?.lvMax)||1));const baseAtk=Number(statAt(detail,'atk',lvl)||0),baseHp=Number(statAt(detail,'hp',lvl)||0);const fouAtk=Math.max(0,Math.min(1000,Number(s.fouAtk)||0)),fouHp=Math.max(0,Math.min(1000,Number(s.fouHp)||0));return{atk:baseAtk+1000+fouAtk,hp:baseHp+1000+fouHp,baseAtk,baseHp,fouAtk,fouHp,lvl}}
function inputOrRead(id,value,min,max){return currentCanEdit()?`<input class="editable-input" id="${id}" type="number" value="${value??''}" min="${min}" max="${max}">`:`<span class="detail-value"><strong>${value??'—'}</strong></span>`}
function openModalBase(r,d,urls,idx){const s=stats(currentPlayer,r.id),st=currentStats(d,r,s),can=currentCanEdit(),cards=commandCards(d,r),coin=coinEstimate(r,s);const gender=genderFix(r,d);const fourHp=Number(s.fouHp)||0,fourAtk=Number(s.fouAtk)||0;
 $('#modal').innerHTML=`<div class="detail-layout"><div class="detail-gallery"><div class="detail-main-art"><img id="detailMainImg" src="${urls[idx]||guessImage(r.atlasId)||''}" alt="${r.name}"></div><div class="art-strip" id="artStrip">${urls.map((u,i)=>`<button class="art-thumb ${i===idx?'active':''}" data-art="${i}"><img src="${u}" alt=""></button>`).join('')}</div><div class="art-controls"><button id="artPrev">←</button><span id="artCounter">${urls.length?`${idx+1} / ${urls.length}`:'0 art'}</span><button id="artNext">→</button></div></div><div class="detail-content"><div class="detail-title-row"><div class="detail-title"><div class="detail-class">${classImg(r.class)}</div><h2>${r.name}</h2><div class="detail-rarity">${rarityNum(r.rarity)}★${isWelfare(r)?' · WELFARE':''}</div><small style="color:#8995a2">${gender}</small></div><div>${coin?`<span class="panel-tag">COINS ${coin.value}${coin.estimated?' ≈':''}</span>`:''}</div>
 <div class="detail-stats">
 <div class="detail-box"><label>NIVEAU</label><div class="detail-value">${inputOrRead('e-level',s.level,1,120)} ${Number(s.grail)>0?`${grailImg()} <small>${s.grail}</small>`:''}</div><div class="sub-stat">${Number(s.grail)||0} graal${Number(s.grail)==1?'':'x'}</div></div>
 <div class="detail-box"><label>NP LEVEL</label><div class="detail-value">${inputOrRead('e-np',s.np,0,99)}</div></div>
 <div class="detail-box"><label>ATTAQUE</label><div class="detail-value"><strong>${st.atk.toLocaleString()}</strong></div><div class="sub-stat">${st.baseAtk.toLocaleString()} base + 1 000 (3★) · 4★ : ${st.fouAtk.toLocaleString()} / 1 000</div>${can?`<input class="micro-edit" id="e-fouatk" type="number" min="0" max="1000" value="${fourAtk}">`:''}</div>
 <div class="detail-box"><label>HP</label><div class="detail-value"><strong>${st.hp.toLocaleString()}</strong></div><div class="sub-stat">${st.baseHp.toLocaleString()} base + 1 000 (3★) · 4★ : ${st.fouHp.toLocaleString()} / 1 000</div>${can?`<input class="micro-edit" id="e-fouhp" type="number" min="0" max="1000" value="${fourHp}">`:''}</div>
 <div class="detail-box"><label>BOND</label><div class="detail-value">${inputOrRead('e-bond',s.bond,0,15)}</div></div>
 <div class="detail-box"><label>GRAALS</label><div class="detail-value">${currentCanEdit()?`<input class="editable-input" id="e-grail" type="number" value="${s.grail??''}" min="0" max="15">`:`<strong>${s.grail??'0'}</strong>`}</div></div>
 </div>
 <div class="command-title">COMMAND CARDS</div><div class="cards-row">${cards.map(c=>cardImg(c)).join('')}</div>
 <div class="levels-title">SKILLS</div><div class="levels-row">${(s.skills||[null,null,null]).map((v,i)=>currentCanEdit()?`<div class="level-cell"><span>SKILL ${i+1}</span><input class="editable-input" id="skill-${i}" type="number" min="0" max="10" value="${v??''}"></div>`:`<div class="level-cell"><span>SKILL ${i+1}</span><div class="level-read">${v??'—'}</div></div>`).join('')}</div>
 <div class="levels-title">APPEND SKILLS</div><div class="levels-row">${(s.appendSkills||[null,null,null,null,null]).map((v,i)=>currentCanEdit()?`<div class="level-cell"><span>APPEND ${i+1}</span><input class="editable-input" id="append-${i}" type="number" min="0" max="10" value="${v??''}"></div>`:`<div class="level-cell"><span>APPEND ${i+1}</span><div class="level-read">${v??'—'}</div></div>`).join('')}</div>
 <div class="modal-footer">${currentCanEdit()?`<span class="readonly-note">Les valeurs modifiables sont enregistrées dans Supabase.</span><div><button id="modalCancel">Annuler</button><button class="save" id="saveServant">Enregistrer</button></div>`:`<span class="readonly-note">Lecture seule · aucune zone d'édition sur ce compte.</span><button id="modalCancel">Fermer</button>`}</div>
 </div></div>`;
 $('#modalCancel').onclick=closeModal;
 let current=idx;function show(i){if(!urls.length)return;current=(i+urls.length)%urls.length;$('#detailMainImg').src=urls[current];$('#artCounter').textContent=`${current+1} / ${urls.length}`;$$('.art-thumb').forEach((b,j)=>b.classList.toggle('active',j===current))}$('#artPrev').onclick=()=>show(current-1);$('#artNext').onclick=()=>show(current+1);$$('.art-thumb').forEach(b=>b.onclick=()=>show(Number(b.dataset.art)));
 if(can)$('#saveServant').onclick=()=>saveModal(idNormalize(r.id));
}
function idNormalize(id){return Number(id)}
async function openServant(id){const r=state.roster.find(x=>Number(x.id)===id);if(!r)return;$('#modal').innerHTML='<div class="modal-loading">CHARGEMENT ATLAS…</div>';$('#modalBackdrop').classList.add('open');const d=await atlasDetail(r),urls=imageList(d);openModalBase(r,d,urls,0);}
async function saveModal(id){const s=ensureStats(currentPlayer,id);s.level=num($('#e-level')?.value);s.np=num($('#e-np')?.value);s.bond=num($('#e-bond')?.value);s.grail=num($('#e-grail')?.value);s.fouHp=Math.max(0,Math.min(1000,num($('#e-fouhp')?.value)||0));s.fouAtk=Math.max(0,Math.min(1000,num($('#e-fouatk')?.value)||0));s.skills=[0,1,2].map(i=>num($('#skill-'+i)?.value));s.appendSkills=[0,1,2,3,4].map(i=>num($('#append-'+i)?.value));localCacheSave();await persistStat(id);closeModal();renderAll();toast('Servant enregistré dans le cloud')}
function closeModal(){$('#modalBackdrop').classList.remove('open')}
function localCacheSave(){localStorage.setItem(localKey,JSON.stringify(state.players))}
function localCacheLoad(){try{const x=JSON.parse(localStorage.getItem(localKey));if(x)for(const p of PLAYERS)if(x[p])state.players[p]=x[p]}catch{}}
function compareStats(p){return{owned:countOwned(p),five:countOwned(p,r=>rarityNum(r.rarity)===5&&!isWelfare(r)),four:countOwned(p,r=>rarityNum(r.rarity)===4&&!isWelfare(r)),wf:countOwned(p,isWelfare),a1:average(p,0),a2:average(p,1),a3:average(p,2),lvl100:countLevel(p,100),lvl120:countLevel(p,120),bond:bond10(p)}}
function renderCompare(){
 const vals=PLAYERS.map((p,i)=>({p,...compareStats(p)})),mx=Math.max(...vals.map(v=>v.owned),1),tones=['#557aa5','#b2744b','#5d967b'];
 $('#compareTop').innerHTML=vals.map((v,i)=>`<article class="person-card"><div class="person-name">${PLAYER_LABELS[v.p]}</div><div class="person-score">${v.owned}</div><small style="color:#8995a2">SERVANTS POSSÉDÉS</small><div class="collection-note"><span>COLLECTION</span><b>${v.owned}</b><small>${collectionPct(v.p).toFixed(1)}% des 4★/5★</small></div><div class="person-meta"><span><small>5★</small><b>${v.five}</b></span><span><small>4★</small><b>${v.four}</b></span><span><small>WELFARE</small><b>${v.wf}</b></span><span><small>BOND 10+</small><b>${v.bond}</b></span></div></article>`).join('');
 initCompareNames();renderShowdown();renderRadar(tones);
}
function initCompareNames(){const r=state.roster.filter(isVisible);$('#compareNames').innerHTML=r.map(x=>`<option value="${x.name}">${x.name}</option>`).join('');}
function renderShowdown(){const r=state.roster.find(x=>Number(x.id)===Number(compareFocusId))||state.roster.find(isVisible);if(!r)return;compareFocusId=r.id;$('#compareSearch').value=r.name;$('#compareFocusTitle').textContent=r.name;$('#compareCards').innerHTML=PLAYERS.map(p=>{const s=stats(p,r.id),own=isOwned(p,r);return `<article class="duel-card"><div class="duel-hero" id="duel-${p}"><div class="loader">ATLAS</div><div class="duel-name">${PLAYER_LABELS[p]}</div></div><div class="duel-body"><div class="duel-row"><span>Possession</span><strong>${own?'Oui':'Non'}</strong></div><div class="duel-row"><span>Niveau</span><strong>${s.level??'—'}</strong></div><div class="duel-row"><span>NP</span><strong>${s.np??'—'}</strong></div><div class="duel-row"><span>Bond</span><strong>${s.bond??'—'}</strong></div><div class="duel-row"><span>S1 / S2 / S3</span><strong>${(s.skills||[]).map(v=>v??'—').join(' · ')}</strong></div><div class="duel-row"><span>Coins</span><strong>${coinEstimate(r,s)?.value??'—'}</strong></div><div class="skill-squares">${(s.skills||[]).map((v,i)=>`<div class="square">S${i+1}<br>${v??'—'}</div>`).join('')}</div></div></article>`}).join('');PLAYERS.forEach(async p=>{const d=await atlasDetail(r);const u=imageList(d)[0]||guessImage(r.atlasId);const e=$(`#duel-${p}`);if(e&&u){const img=new Image();img.onload=()=>{e.innerHTML=`<img src="${u}" alt=""><div class="duel-name">${PLAYER_LABELS[p]}</div>`};img.src=u}})}
function radarPolygon(values,cx,cy,r){return values.map((v,i)=>{const a=-Math.PI/2+i*(Math.PI*2/values.length);return [cx+Math.cos(a)*r*v,cy+Math.sin(a)*r*v]}).map(p=>p.join(',')).join(' ')}
function renderRadar(colors){const labels=['Collection','Skill 1','Skill 2','Skill 3','Lv 120','Bond 10+'];const points=labels.length,cx=310,cy=250,rad=165;const coords=i=>{const a=-Math.PI/2+i*(Math.PI*2/points);return [cx+Math.cos(a)*rad,cy+Math.sin(a)*rad]};const axes=labels.map((l,i)=>{const [x,y]=coords(i),a=-Math.PI/2+i*(Math.PI*2/points),tx=cx+Math.cos(a)*(rad+30),ty=cy+Math.sin(a)*(rad+30);return `<line x1="${cx}" y1="${cy}" x2="${x}" y2="${y}" stroke="#cfd8e1"/><text x="${tx}" y="${ty}" text-anchor="middle" dominant-baseline="middle" class="radar-label">${l}</text>`}).join('');const rings=[.25,.5,.75,1].map(v=>`<polygon points="${Array.from({length:points},(_,i)=>{const a=-Math.PI/2+i*(Math.PI*2/points);return [cx+Math.cos(a)*rad*v,cy+Math.sin(a)*rad*v].join(',')}).join(' ')}" fill="none" stroke="#dfe5eb"/>`).join('');const all=PLAYERS.map((p,i)=>{const s=compareStats(p);const vals=[Math.min(1,collectionPct(p)/100),s.a1/10,s.a2/10,s.a3/10,Math.min(1,s.lvl120/10),Math.min(1,s.bond/10)];const pts=radarPolygon(vals,cx,cy,rad);const dots=vals.map((v,j)=>{const a=-Math.PI/2+j*(Math.PI*2/points);return `<circle cx="${cx+Math.cos(a)*rad*v}" cy="${cy+Math.sin(a)*rad*v}" r="5" fill="${colors[i]}" class="radar-point"/>`}).join('');return{p,pts,dots,color:colors[i]}});$('#radarLegend').innerHTML=all.map(x=>`<span class="legend-item"><i class="legend-dot" style="background:${x.color}"></i><b>${PLAYER_LABELS[x.p]}</b></span>`).join('');$('#compareRadar').innerHTML=`<svg class="radar-svg" viewBox="0 0 620 510" role="img">${rings}${axes}<circle cx="${cx}" cy="${cy}" r="4" fill="#637181"/>${all.map(x=>`<polygon points="${x.pts}" fill="${x.color}" fill-opacity=".12" stroke="${x.color}" stroke-width="3"/>${x.dots}`).join('')}</svg>`}
function renderSupports(){
 supportPlayer=currentPlayer;const fid=supportLocal[supportPlayer]?.friendId||'';$('#supportFriendId').value=fid;$('#rayshiftLink').href=fid?`https://rayshift.io/na/${fid.replace(/\D/g,'')}`:'https://rayshift.io/lookup';
 $('#supportMasterTabs').innerHTML=PLAYERS.map(p=>`<button class="support-tab ${p===supportPlayer?'active':''}" data-support-player="${p}">${PLAYER_LABELS[p]}</button>`).join('');$$('[data-support-player]').forEach(b=>b.onclick=()=>{supportPlayer=b.dataset.supportPlayer;renderSupports()});
 const frame=$('#rayFrameWrap');if(fid){frame.innerHTML=`<iframe class="ray-frame" src="https://rayshift.io/na/${fid.replace(/\D/g,'')}" title="Rayshift ${PLAYER_LABELS[supportPlayer]}"></iframe>`}else{frame.innerHTML='<div class="empty-state"><strong>Aucun Friend ID</strong><span>Ajoute le Friend ID NA pour afficher le profil public.</span></div>'}
 const lists=Array.from({length:6},(_,i)=>({name:`${i<3?'Normal':'Event'} ${i%3+1}`,event:i>=3}));$('#supportLists').innerHTML=lists.map(l=>`<article class="support-list"><div class="support-list-head"><div><h3>${l.name}</h3><small>${l.event?'Liste événement':'Liste normale'}</small></div><span class="support-status">${fid?'RAYSHIFT':'À CONFIGURER'}</span></div><div class="support-placeholder"><strong>6 positions</strong><span>La liste live est gérée par Rayshift.</span><a href="${fid?`https://rayshift.io/na/${fid.replace(/\D/g,'')}`:'https://rayshift.io/lookup'}" target="_blank" rel="noopener">Ouvrir cette liste ↗</a></div></article>`).join('');
}
function navigate(v){currentView=v;$$('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+v));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#pageName').textContent={overview:'Overview',servants:'Servants',compare:'Compare',supports:'Support Lists'}[v];$('#sidebar').classList.remove('open');renderAll()}
function renderAll(){renderMasterSwitch();if(currentView==='overview')renderOverview();if(currentView==='servants'){fillFilters();renderRoster()}if(currentView==='compare')renderCompare();if(currentView==='supports')renderSupports()}
async function persistStat(id){if(!cloudEnabled||!cloud||!session||!currentCanEdit())return;const s=stats(currentPlayer,id);const body={player_key:currentPlayer,servant_id:Number(id),level:s.level,np:s.np,bond:s.bond,grail:s.grail,fou_hp:s.fouHp,fou_atk:s.fouAtk,servant_coins:s.servantCoins,skills:s.skills,append_skills:s.appendSkills,updated_at:new Date().toISOString()};const {error}=await cloud.from('chaldea_stats').upsert(body,{onConflict:'player_key,servant_id'});if(error)toast('Erreur Supabase : '+error.message);else{updateSync('Cloud · synchronisé');await refreshPublicStats()}}
async function refreshPublicStats(){if(!cloudEnabled||!cloud)return;const {data,error}=await cloud.from('chaldea_stats').select('*');if(error){updateSync('Lecture cloud refusée',true);return}for(const x of data||[]){const ss=ensureStats(x.player_key,x.servant_id);ss.level=x.level;ss.np=x.np;ss.bond=x.bond;ss.grail=x.grail;ss.fouHp=x.fou_hp;ss.fouAtk=x.fou_atk;ss.servantCoins=x.servant_coins;ss.skills=x.skills||[null,null,null];ss.appendSkills=x.append_skills||[null,null,null,null,null]}localCacheSave();renderAll()}
async function seedCurrentPlayer(){if(!cloudEnabled||!cloud||!session||!currentAuth?.canEdit)return;const ids=Object.entries(state.players[currentPlayer]?.stats||{});for(let i=0;i<ids.length;i+=50){const chunk=ids.slice(i,i+50).map(([id,s])=>({player_key:currentPlayer,servant_id:Number(id),level:s.level,np:s.np,bond:s.bond,grail:s.grail,fou_hp:s.fouHp,fou_atk:s.fouAtk,servant_coins:s.servantCoins,skills:s.skills||[null,null,null],append_skills:s.appendSkills||[null,null,null,null,null]}));const {error}=await cloud.from('chaldea_stats').upsert(chunk,{onConflict:'player_key,servant_id'});if(error){toast('Import impossible : '+error.message);return}}toast('Snapshot importé dans Supabase');await refreshPublicStats()}
async function loadSupportProfiles(){if(!cloudEnabled||!cloud)return;const {data,error}=await cloud.from('chaldea_support_profiles').select('*');if(error)return;for(const x of data||[])supportLocal[x.player_key]={friendId:x.friend_id||''}}
async function saveSupportProfile(p,fid){if(!cloudEnabled||!cloud||!session||!currentAuth?.canEdit||currentAuth.playerKey!==p){localCacheSave();return}const {error}=await cloud.from('chaldea_support_profiles').upsert({player_key:p,friend_id:fid||null,updated_at:new Date().toISOString()},{onConflict:'player_key'});if(error)toast('Erreur Support : '+error.message);else toast('Friend ID synchronisé')}
async function loadCloud(){if(!cloudEnabled||!cloud)return;await refreshPublicStats();await loadSupportProfiles();const {data}=await cloud.from('chaldea_stats').select('player_key');const counts={};(data||[]).forEach(x=>counts[x.player_key]=(counts[x.player_key]||0)+1);if(session&&currentAuth?.canEdit&&!counts[currentAuth.playerKey])showSeedBanner()}
function showSeedBanner(){if($('#seedBanner'))return;const div=document.createElement('div');div.id='seedBanner';div.className='seed-banner';div.innerHTML=`<span>Ton compte n’a pas encore été initialisé dans la base cloud.</span><button>Importer ton snapshot Excel</button>`;div.querySelector('button').onclick=async()=>{await seedCurrentPlayer();div.remove()};document.body.appendChild(div)}
async function resolveMembership(){if(!cloud||!session)return;const {data,error}=await cloud.from('chaldea_members').select('auth_user_id,player_key,display_name,can_edit').eq('auth_user_id',session.user.id).maybeSingle();if(error){currentAuth=null;updateSync('Compte non associé',true);return}currentAuth=data?{playerKey:data.player_key,canEdit:!!data.can_edit}:null;if(data&&state.players[data.player_key])state.players[data.player_key].displayName=data.display_name||PLAYER_LABELS[data.player_key];updateEditVisibility()}
async function claimJulien(){if(!cloud||!session)return;const {data,error}=await cloud.rpc('claim_julien');if(error){toast(error.message);return}await resolveMembership();renderAll();toast('Compte associé à Julien')}
async function setupCloud(){if(!CONFIG.supabaseUrl||!CONFIG.supabaseAnonKey||!window.supabase)return;cloud=window.supabase.createClient(CONFIG.supabaseUrl,CONFIG.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});cloudEnabled=true;const got=await cloud.auth.getSession();session=got.data.session||null;if(session){await resolveMembership();updateSync(currentAuth?.canEdit?'Cloud · éditeur':currentAuth?'Cloud · lecteur':'Compte connecté · non associé');await loadCloud()}else{updateSync('Cloud · lecture publique');await refreshPublicStats();await loadSupportProfiles()}cloud.auth.onAuthStateChange((_event,ses)=>{setTimeout(async()=>{session=ses;currentAuth=null;if(ses){await resolveMembership();updateSync(currentAuth?.canEdit?'Cloud · éditeur':currentAuth?'Cloud · lecteur':'Compte connecté · non associé');await loadCloud()}else{updateSync('Cloud · lecture publique');await refreshPublicStats();await loadSupportProfiles();renderAll()}},0)});cloud.channel('chaldea-live').on('postgres_changes',{event:'*',schema:'public',table:'chaldea_stats'},()=>refreshPublicStats()).subscribe()}
function accountUI(){const logged=!!session;const can=currentCanEdit();const missing=logged&&!currentAuth;$('#modal').innerHTML=`<div style="padding:24px"><span class="eyebrow">CLOUD ACCESS</span><h2 style="font:700 26px 'Space Grotesk';margin:6px 0 0">${logged?'Compte Supabase':'Connexion'}</h2><p class="account-copy">${logged?`${session.user.email}<br>${can?`Éditeur · ${PLAYER_LABELS[currentAuth.playerKey]}`:missing?'Compte authentifié mais pas encore associé à un Master.':'Lecture seule'}`:'Connecte ton compte Supabase. Le site reste consultable sans compte.'}</p>${logged?(missing?`<div class="claim-box"><b>Compte Julien</b><span>Tu peux associer ce compte à Julien si aucun compte Julien n’est déjà lié.</span><button class="save" id="claimJulien">Associer à Julien</button></div>`:`<div class="modal-footer"><button id="modalCancel">Fermer</button><button class="save" id="logout">Se déconnecter</button></div>`):`<div style="display:grid;gap:10px;margin-top:16px"><input id="loginEmail" class="editable-input" type="email" placeholder="Email"><input id="loginPassword" class="editable-input" type="password" placeholder="Mot de passe"></div><div class="modal-footer"><button id="modalCancel">Annuler</button><button class="save" id="login">Se connecter</button></div>`}</div>`;$('#modalBackdrop').classList.add('open');$('#modalCancel').onclick=closeModal;if(logged&&missing){$('#claimJulien').onclick=claimJulien}else if(logged){$('#logout').onclick=async()=>{await cloud.auth.signOut();closeModal()}}else{$('#login').onclick=async()=>{const {error}=await cloud.auth.signInWithPassword({email:$('#loginEmail').value,password:$('#loginPassword').value});if(error)toast(error.message);else closeModal()}}}
$('#modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()};
$$('.nav-item').forEach(b=>b.onclick=()=>navigate(b.dataset.view));$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');$('#accountBtn').onclick=accountUI;$('#searchInput').oninput=renderRoster;$('#sortFilter').onchange=renderRoster;$('#sortDir').onclick=()=>{sortDir=sortDir==='desc'?'asc':'desc';$('#sortDir').textContent=sortDir==='asc'?'↑ Ascendant':'↓ Descendant';renderRoster()};$$('[data-roster-mode]').forEach(b=>b.onclick=()=>{rosterMode=b.dataset.rosterMode;$$('[data-roster-mode]').forEach(x=>x.classList.toggle('active',x===b));renderRoster()});$$('[data-pop]').forEach(b=>b.onclick=e=>{$$('.filter-pop.open').forEach(x=>x.classList.remove('open'));$('#'+b.dataset.pop).classList.toggle('open');e.stopPropagation()});document.addEventListener('click',e=>{$$('.filter-pop.open').forEach(p=>{if(!p.parentElement.contains(e.target))p.classList.remove('open')})});$('#compareSearch').onchange=e=>{const q=norm(e.target.value);const exact=state.roster.find(r=>isVisible(r)&&norm(r.name)===q)||state.roster.find(r=>isVisible(r)&&norm(r.name).includes(q));if(exact){compareFocusId=exact.id;renderShowdown()}};$('#supportFriendId').oninput=e=>{supportLocal[supportPlayer].friendId=e.target.value.replace(/\D/g,'')};$('#saveFriendId').onclick=async()=>{const fid=supportLocal[supportPlayer].friendId||'';await saveSupportProfile(supportPlayer,fid);renderSupports()};
localCacheLoad();PLAYERS.forEach(p=>state.players[p]??={displayName:PLAYER_LABELS[p],stats:{}});fillFilters();renderAll();setupCloud();syncRosterNA();
