import initialState from './data/initial-state.json' with { type: 'json' };
import welfareData from './data/welfare-ids.json' with { type: 'json' };
const CONFIG=window.CHALDEA_CONFIG||{};
const PLAYERS=['julien','yanis','attmann'];
const CLASS_ORDER=['Saber','Archer','Lancer','Rider','Caster','Assassin','Berserker','Ruler','Avenger','Alter Ego','Moon Cancer','Foreigner','Pretender','Shielder','Beast'];
const FUTURE_IDS=new Set(initialState.settings?.futureExcludedIds||[426,427,428,429,431]);
const NON_COUNTED=new Set(initialState.settings?.nonCountedIds||[1]);
const state=structuredClone(initialState);
let currentPlayer='julien', currentView='overview', rosterMode='cards', sortDir='desc', compareFocusId=null, compareSearchTimer=null;
let atlasFull=new Map(), atlasById=new Map(), imageObserver=null;
let cloud=null, session=null, currentAuth=null, cloudEnabled=false;
const selectedClasses=new Set(), selectedRarities=new Set();
const supportState={julien:{friendId:'',lists:[]},yanis:{friendId:'',lists:[]},attmann:{friendId:'',lists:[]}};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const toast=m=>{const e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)};
const num=v=>{if(v===null||v===undefined||v==='')return null;const x=Number(v);return Number.isFinite(x)?x:null};
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const WELFARE_NAMES=new Set((welfareData.names||[]).map(norm));
const WELFARE_IDS=new Set((welfareData.ids||initialState.welfareIds||[]).map(Number));
function rarityNum(r){return r==='SSR'?5:r==='SR'?4:r==='R'?3:r==='UC'?2:1}
function isWelfare(r){return WELFARE_IDS.has(Number(r.id))||r.rarity==='Welfare'||WELFARE_NAMES.has(norm(r.name))}
function isCounted(r){return !NON_COUNTED.has(Number(r.id)) && !r.nonCounted && classKey(r.class)!=='Extra'}
function stats(p,id){return state.players[p]?.stats?.[String(id)]||{level:null,np:null,bond:null,grail:null,fouHp:null,fouAtk:null,servantCoins:null,skills:[null,null,null],appendSkills:[null,null,null,null,null]}}
function isOwned(p,r){if(!isCounted(r))return true;const s=stats(p,r.id);return ['level','np','bond','grail','fouHp','fouAtk','servantCoins'].some(k=>s[k]!=null)||[...(s.skills||[]),...(s.appendSkills||[])].some(v=>v!=null)}
function validSkill(v){return Number.isFinite(v)&&v>=1&&v<=10}
function skillVals(p,idx=null){const all=[];state.roster.forEach(r=>{if(!isCounted(r))return;const s=stats(p,r.id);(idx===null?s.skills:[s.skills?.[idx]]).flat().forEach(v=>{if(validSkill(v))all.push(v)})});return all}
function avg(p,idx=null){const a=skillVals(p,idx);return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}
function skillDist(p){const a=Array(11).fill(0);skillVals(p).forEach(v=>a[v]++);return a}
function countOwned(p,pred=()=>true){return state.roster.filter(r=>isCounted(r)&&pred(r)&&isOwned(p,r)).length}
function countMax(p,l){return state.roster.filter(r=>isCounted(r)&&isOwned(p,r)&&Number(stats(p,r.id).level)===l).length}
function bond10(p){return state.roster.filter(r=>isCounted(r)&&isOwned(p,r)&&Number(stats(p,r.id).bond)>=10).length}
function grailCount(s){return Math.max(0,Number(s.grail)||0)}
function coinEstimate(r,s){if(!isCounted(r)||!isOwned(currentPlayer,r)||rarityNum(r.rarity)<4)return null; if(s.servantCoins!=null)return {value:s.servantCoins,estimated:false}; const copies=Math.max(0,Number(s.np)||0); const base=rarityNum(r.rarity)===5?90:50; const bond=Math.max(0,(Number(s.bond)||0)-5)*5; const append=(s.appendSkills||[]).filter(v=>validSkill(v)).length*20; const grail=Number(s.grail)||0; return {value:Math.max(0,copies*base+bond+append+Math.max(0,grail-4)*20),estimated:true}}
function classKey(c){c=String(c||'').replace(/\n/g,' ').trim();return c==='Moon Cancer'?'Moon Cancer':c}
function classIcon(c){const shapes={
Saber:'<path d="M11 1l2 2-7 7 2 2 7-7 2 2-9 9H6l-5-5V9l2-2 2 2 6-6z"/>',
Archer:'<path d="M5 18c6-2 6-12 0-14M5 18l12-4M17 14l-2-2m2 2 2 1m-4-5 3-1"/>',
Lancer:'<path d="M12 2v16m0-12 4 4-4 4-4-4 4-4m0 0V2m0 16 3 3M9 21l3-3"/>',
Rider:'<path d="M4 16c2-5 4-8 8-8s6 3 8 8M6 18h12M8 13h8m-9 5-2 2m12-2 2 2"/>',
Caster:'<path d="M12 2l2 5 5 2-5 2-2 7-2-7-5-2 5-2zM18 13l1 2 2 1-2 1-1 2-1-2-2-1 2-1z"/>',
Assassin:'<path d="M4 20l16-16M8 4h12v12M4 8v8l8 8"/>',
Berserker:'<path d="M4 4l8 16L20 4l-4 1-4-3-4 3zM8 15l4 1 4-1"/>',
Ruler:'<path d="M7 20V9m0 0a5 5 0 0 1 10 0v11M5 20h14M9 9h6"/>',
Avenger:'<path d="M12 3l7 4v6l-7 8-7-8V7zM9 11h6M10 15h4"/>',
'Alter Ego':'<path d="M4 7l8-4 8 4-8 4zM4 7v10l8 4 8-4V7m-8 4v10"/>',
'Moon Cancer':'<path d="M18 5a7 7 0 1 0 1 9A6 6 0 0 1 12 5a7 7 0 0 0 6 0z"/>',
Foreigner:'<path d="M12 2c3 4 7 5 8 5-1 8-4 12-8 15-4-3-7-7-8-15 1 0 5-1 8-5zM8 11h8M10 8h4m-4 6h4"/>',
Pretender:'<path d="M6 4h12l2 5-4 7v4H8v-4l-4-7zM8 9h8M9 20h6"/>',
Shielder:'<path d="M12 2l8 3v6c0 5-3 8-8 11-5-3-8-6-8-11V5zM8 11h8M12 7v8"/>',
Beast:'<path d="M4 12l4-6 4 4 4-4 4 6-4 7H8zM9 13h6"/>'};
return `<span class="class-icon" title="${c}"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">${shapes[c]||shapes.Saber}</svg></span>`}

function normalizeRarity(r){return r==='Welfare'?'SR':r}
function ownedSet(p){return new Set(state.roster.filter(r=>isCounted(r)&&isOwned(p,r)).map(r=>r.id))}
function renderMasterSwitch(){
 $('#masterSwitch').innerHTML=PLAYERS.map(p=>`<button class="master-tab ${p===currentPlayer?'active':''}" data-player="${p}">${state.players[p]?.displayName||p}</button>`).join('');
 $$('.master-tab').forEach(b=>b.onclick=()=>{currentPlayer=b.dataset.player;updateEditVisibility();renderAll()});
 $('#heroMaster').textContent=state.players[currentPlayer]?.displayName||currentPlayer;
}
function currentCanEdit(){return !!currentAuth && !!currentAuth.canEdit && currentAuth.playerKey===currentPlayer}
function updateEditVisibility(){const can=currentCanEdit();$('#editRosterBtn').hidden=!can; document.body.classList.toggle('editor',can)}
function renderOverview(){
 const p=currentPlayer; const all=countOwned(p), five=countOwned(p,r=>r.rarity==='SSR'&&!isWelfare(r)), four=countOwned(p,r=>r.rarity==='SR'&&!isWelfare(r)), wf=countOwned(p,r=>isWelfare(r));
 $('#introOwned').textContent=all; $('#introDate').textContent='NA';
 const kpis=[['OWNED',all],['5★',five],['4★',four],['WELFARE',wf],['LV 120',countMax(p,120)],['LV 100',countMax(p,100)],['BOND 10+',bond10(p)]];
 $('#overviewMetrics').innerHTML=kpis.map(([a,b])=>`<div class="kpi"><small>${a}</small><strong>${b}</strong><i>${a==='OWNED'?'Servants comptés':a==='BOND 10+'?'Masters bonds':a==='WELFARE'?'Servants gratuits':'Compte actuel'}</i></div>`).join('');
 $('#rarityDisplay').innerHTML=`<div class="rarity-card"><span class="label">5 STAR</span><span class="stars">★★★★★</span><span class="value">${five}</span></div><div class="rarity-card"><span class="label">4 STAR</span><span class="stars">★★★★</span><span class="value">${four}</span></div><div class="rarity-card welfare"><span class="label">WELFARE</span><span class="stars">FREE</span><span class="value">${wf}</span></div>`;
 const dist=skillDist(p), max=Math.max(...dist.slice(1),1), rows=[];for(let lvl=10;lvl>=1;lvl--)rows.push(`<div class="skill-row"><span class="skill-level">${lvl}</span><div class="skill-track"><div class="skill-fill" style="width:${(dist[lvl]/max*100).toFixed(1)}%"></div></div><b>${dist[lvl]}</b></div>`);$('#skillBars').innerHTML=rows.join('');$('#skillsAverage').textContent=avg(p).toFixed(1);
 const detail=[['MOY. SKILL 1',avg(p,0)],['MOY. SKILL 2',avg(p,1)],['MOY. SKILL 3',avg(p,2)],['BOND 10+',bond10(p)],['NIVEAU 120',countMax(p,120)],['NP MAX',countOwned(p,r=>Number(stats(p,r.id).np)>=5)]];
 $('#detailStats').innerHTML=detail.map(([a,b])=>`<div class="detail-cell"><small>${a}</small><strong>${typeof b==='number'?(a.includes('MOY')?b.toFixed(1):b):b}</strong></div>`).join('');
 const incomplete=state.roster.filter(r=>isCounted(r)&&isOwned(p,r)&&skillValsFor(stats(p,r.id)).filter(validSkill).length<3).length;
 const noBond=countOwned(p,r=>Number(stats(p,r.id).bond||0)<10); const noGrail=countOwned(p,r=>Number(stats(p,r.id).level||0)>=120&&Number(stats(p,r.id).grail||0)<15);
 const insight=[['Skills incomplets',incomplete],['Possédés sous Bond 10',noBond],['Lv 120 non maxés au Graal 15',noGrail],['Welfares',wf]].map(([a,b])=>`<div class="insight"><i></i><b>${a}</b><span>${b}</span></div>`);$('#accountInsight').innerHTML=insight.join('');
}
function skillValsFor(s){return (s.skills||[]).filter(v=>validSkill(v))}
function fillFilters(){
 const classes=[...new Set(state.roster.filter(r=>!NON_COUNTED.has(Number(r.id))).map(r=>classKey(r.class)).filter(c=>c&&c!=='Extra'))].sort((a,b)=>CLASS_ORDER.indexOf(a)-CLASS_ORDER.indexOf(b));
 const classPop=$('#classPop');classPop.innerHTML=classes.map(c=>`<label class="check-item"><input type="checkbox" data-class="${c}" ${selectedClasses.has(c)?'checked':''}>${classIcon(c)}<span>${c}</span></label>`).join('');
 const rarities=[['5','5★'],['4','4★'],['3','3★'],['2','2★'],['1','1★'],['welfare','Welfare']];$('#rarityPop').innerHTML=rarities.map(([v,l])=>`<label class="check-item"><input type="checkbox" data-rarity="${v}" ${selectedRarities.has(v)?'checked':''}><span>${l}</span></label>`).join('');
 $$('#classPop input').forEach(i=>i.onchange=()=>{i.checked?selectedClasses.add(i.dataset.class):selectedClasses.delete(i.dataset.class);updateFilterLabels();renderRoster()});$$('#rarityPop input').forEach(i=>i.onchange=()=>{i.checked?selectedRarities.add(i.dataset.rarity):selectedRarities.delete(i.dataset.rarity);updateFilterLabels();renderRoster()});updateFilterLabels();
}
function updateFilterLabels(){$('#classFilterCount').textContent=selectedClasses.size?`(${selectedClasses.size})`:'';$('#rarityFilterCount').textContent=selectedRarities.size?`(${selectedRarities.size})`:''}
function closePops(e){$$('.filter-pop.open').forEach(p=>{if(!p.parentElement.contains(e.target))p.classList.remove('open')})}
function sortRows(rows){const mode=$('#sortFilter').value;const sign=sortDir==='asc'?1:-1;return rows.sort((a,b)=>{let x=0,y=0;if(mode==='bond'){x=Number(a.s.bond)||-1;y=Number(b.s.bond)||-1}else if(mode==='np'){x=Number(a.s.np)||-1;y=Number(b.s.np)||-1}else if(mode==='level'){x=Number(a.s.level)||-1;y=Number(b.s.level)||-1}else if(mode==='rarity-level'){x=(rarityNum(a.r.rarity)*10000)+(Number(a.s.level)||0);y=(rarityNum(b.r.rarity)*10000)+(Number(b.s.level)||0)}else{x=Number(a.r.id);y=Number(b.r.id)}return (x-y)*sign})}
function renderRoster(){
 const q=norm($('#searchInput').value), rows=state.roster.filter(r=>!NON_COUNTED.has(Number(r.id))&&!FUTURE_IDS.has(Number(r.id))).map(r=>({r,s:stats(currentPlayer,r.id)})).filter(o=>{const cls=classKey(o.r.class), rar=isWelfare(o.r)?'welfare':String(rarityNum(normalizeRarity(o.r.rarity)));return (!q||norm(o.r.name).includes(q))&&(!selectedClasses.size||selectedClasses.has(cls))&&(!selectedRarities.size||selectedRarities.has(rar))});
 sortRows(rows);$('#rosterCount').textContent=`${rows.length} affichés`;$('#rosterSummary').textContent=`${countOwned(currentPlayer)} possédés · ${state.roster.filter(r=>isCounted(r)).length-countOwned(currentPlayer)} manquants`;
 $('#rosterCards').classList.toggle('hidden',rosterMode!=='cards');$('#rosterTable').classList.toggle('hidden',rosterMode!=='table');
 if(rosterMode==='cards'){
   $('#rosterCards').innerHTML=rows.map(({r,s})=>{const own=isOwned(currentPlayer,r), np=s.np==null?'—':Math.min(5,Math.max(0,Number(s.np))); const grail=grailCount(s); return `<article class="servant-card ${own?'owned':'missing'}" data-servant-id="${r.id}">${own?'':'<span class="missing-ribbon">NON POSSÉDÉ</span>'}<div class="card-art"><div class="loader">LOADING</div></div><div class="card-content"><div class="card-topline"><span class="rarity-short">${rarityNum(normalizeRarity(r.rarity))}★${isWelfare(r)?' · W':''}</span>${classIcon(classKey(r.class))}</div><div class="card-name">${r.name}</div><div class="card-line"><span>Lv ${s.level??'—'} ${grail?`<span class="grail-mini">${grailSvg()} ${grail}</span>`:''}</span><span class="np-chip">NP ${np}</span></div></div></article>`}).join('');observeCards(rows.map(x=>x.r));
 }else{
   $('#rosterTable').innerHTML=`<table class="table"><thead><tr><th>Servant</th><th>Classe</th><th>Rareté</th><th>Lv</th><th>NP</th><th>S1</th><th>S2</th><th>S3</th><th>Bond</th><th>Coins</th><th>État</th></tr></thead><tbody>${rows.map(({r,s})=>`<tr data-servant-id="${r.id}" class="${isOwned(currentPlayer,r)?'':'missing-row'}"><td class="name">${r.name}</td><td>${classIcon(classKey(r.class))}</td><td class="stars">${rarityNum(normalizeRarity(r.rarity))}★${isWelfare(r)?' · W':''}</td><td>${s.level??'—'}</td><td class="np">${s.np??'—'}</td><td>${s.skills?.[0]??'—'}</td><td>${s.skills?.[1]??'—'}</td><td>${s.skills?.[2]??'—'}</td><td>${s.bond??'—'}</td><td>${coinEstimate(r,s)?.value??'—'}</td><td>${isOwned(currentPlayer,r)?'Possédé':'Manquant'}</td></tr>`).join('')}</tbody></table>`;
 }
 $$('.servant-card,.table tr[data-servant-id]').forEach(el=>el.onclick=()=>openServant(Number(el.dataset.servantId)));
}
function grailSvg(){return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M7 4h10l-1 8c-.2 2-1.6 4-4 4s-3.8-2-4-4zM5 4h2m10 0h2M9 19h6m-8 2h10M9 7H5c0 2 1 4 4 4m6-4h4c0 2-1 4-4 4"/></svg>'}
function getAtlasSearchName(r){return atlasNameFix(r.name)}
function atlasNameFix(name){return String(name||'').replace(/\n/g,' ').replace(/\s+/g,' ').replace('Altria','Altria').trim()}
async function fetchAtlasBasic(){
 try{const res=await fetch('https://api.atlasacademy.io/export/NA/basic_servant.json',{cache:'no-store'});if(!res.ok)throw new Error(res.status);const arr=await res.json();return Array.isArray(arr)?arr:null}catch{return null}}
async function syncRosterNA(){
 const arr=await fetchAtlasBasic();if(!arr){$('#atlasStatus').textContent='ATLAS / NA · hors ligne';return}
 const valid=arr.filter(x=>Number(x.collectionNo)>1&&x.name&&!FUTURE_IDS.has(Number(x.collectionNo))); const byId=new Map(valid.map(x=>[Number(x.collectionNo),x]));
 // Atlas is authoritative for NA roster. Keep Excel stats only for IDs that are currently NA.
 state.roster=state.roster.filter(r=>Number(r.id)===1||byId.has(Number(r.id))||Number(r.id)<2);
  const allowed=new Set(valid.map(x=>Number(x.collectionNo))); state.roster=state.roster.filter(r=>Number(r.id)===1||allowed.has(Number(r.id)));

 let added=0;valid.forEach(x=>{const id=Number(x.collectionNo);if(id===1)return;const cls=normalizeAtlasClass(x.className);if(cls==='Extra')return;let r=state.roster.find(y=>Number(y.id)===id);if(!r){state.roster.push({id,name:x.name,class:cls,rarity:atlasRarity(x),attribute:x.attribute||'',cardType:x.cardType||'',target:x.target||''});PLAYERS.forEach(p=>state.players[p].stats[String(id)] ||= {skills:[null,null,null],appendSkills:[null,null,null,null,null]});added++}else{r.name=x.name;r.class=cls;r.rarity=atlasRarity(x)}});state.roster.sort((a,b)=>Number(a.id)-Number(b.id));saveLocal();fillFilters();renderAll();$('#atlasStatus').textContent=`ATLAS / NA · ${valid.length} Servants`;if(added)toast(`${added} nouveau(x) Servant(s) NA ajouté(s)`)}
function normalizeAtlasClass(c){const s=String(c||'').toLowerCase().replace(/[^a-z]/g,'');const m={saber:'Saber',archer:'Archer',lancer:'Lancer',rider:'Rider',caster:'Caster',assassin:'Assassin',berserker:'Berserker',ruler:'Ruler',avenger:'Avenger',alterego:'Alter Ego',mooncancer:'Moon Cancer',foreigner:'Foreigner',pretender:'Pretender',shielder:'Shielder',beast:'Beast'};return m[s]||'Extra'}
function atlasRarity(x){return Number(x.rarity)>=5?'SSR':Number(x.rarity)===4?'SR':Number(x.rarity)===3?'R':Number(x.rarity)===2?'UC':'C'}
async function atlasDetail(r){if(atlasFull.has(r.id))return atlasFull.get(r.id);const p=(async()=>{try{const res=await fetch(`https://api.atlasacademy.io/nice/NA/servant/${Number(r.id)}`,{cache:'force-cache'});if(!res.ok)throw 0;return await res.json()}catch{return null}})();atlasFull.set(r.id,p);return p}
function collectImageUrls(detail){const out=[];const add=v=>{if(typeof v==='string'&&/^https?:\/\//.test(v)&&/\.(png|jpg|jpeg|webp)(\?|$)/i.test(v))out.push(v)};const walk=(v)=>{if(!v)return;if(typeof v==='string'){add(v);return}if(Array.isArray(v)){v.forEach(walk);return}if(typeof v==='object'){for(const [k,x] of Object.entries(v)){if(['ascension','costume','charaGraph','costumeGraph','commands','card','faces'].includes(k)||typeof x==='object')walk(x)}}};walk(detail?.extraAssets?.charaGraph?.ascension);walk(detail?.extraAssets?.charaGraph?.costume);walk(detail?.extraAssets?.costume);walk(detail?.extraAssets?.faces);return [...new Set(out)]}
function commandCards(detail,r){const deck=Array.isArray(detail?.cardDeck)?detail.cardDeck.map(x=>String(x).charAt(0).toUpperCase()):Array.isArray(detail?.cards)?detail.cards.map(x=>String(x).charAt(0).toUpperCase()):[];if(deck.length>=5)return deck.slice(0,5);const ct=String(r.cardType||'Buster').toLowerCase();const map={buster:['B','B','B','A','Q'],arts:['A','A','A','B','Q'],quick:['Q','Q','Q','A','B']};return map[ct]||map.buster}
function growthStat(detail,kind,level){const base=Number(detail?.[kind+'Base']);const max=Number(detail?.[kind+'Max']);if(!Number.isFinite(base)||!Number.isFinite(max))return null;const growth=detail?.[kind==='atk'?'atkGrowth':'hpGrowth'];if(Array.isArray(growth)&&growth.length){const idx=Math.min(growth.length-1,Math.max(0,Math.round(level)-1));const v=Number(growth[idx]);if(Number.isFinite(v))return v}const ratio=Math.max(0,Math.min(1,(Number(level)-1)/Math.max(1,(Number(detail?.lvMax)||100)-1)));return Math.round(base+(max-base)*ratio)}
function calcStats(detail,r,s){const level=Math.max(1,Number(s.level)||Number(detail?.lvMax)||1);const atk=growthStat(detail,'atk',level),hp=growthStat(detail,'hp',level);return {level,atk:atk==null?null:atk+(Number(s.fouAtk)||0),hp:hp==null?null:hp+(Number(s.fouHp)||0)}}
function lazyImage(el,url){const img=new Image();img.src=url;img.alt='';img.onload=()=>{img.classList.add('ready');el.innerHTML='';el.appendChild(img)};img.onerror=()=>{el.querySelector('.loader')?.remove();el.innerHTML='<span class="loader">NO ART</span>'}}
function observeCards(rows){if(imageObserver)imageObserver.disconnect();imageObserver=new IntersectionObserver(entries=>{entries.forEach(async en=>{if(!en.isIntersecting)return;const el=en.target;imageObserver.unobserve(el);const id=Number(el.dataset.servantId),r=state.roster.find(x=>Number(x.id)===id);const d=await atlasDetail(r);const url=collectImageUrls(d)[0];if(url)lazyImage(el.querySelector('.card-art'),url);})},{rootMargin:'1200px'});$$('.servant-card').forEach(x=>imageObserver.observe(x))}
function initCompareNames(){$('#compareNames').innerHTML=state.roster.filter(r=>isCounted(r)).map(r=>`<option value="${r.name}">`).join('')}
function compareStats(p){return{owned:countOwned(p),five:countOwned(p,r=>r.rarity==='SSR'&&!isWelfare(r)),four:countOwned(p,r=>r.rarity==='SR'&&!isWelfare(r)),wf:countOwned(p,isWelfare),a1:avg(p,0),a2:avg(p,1),a3:avg(p,2),lvl100:countMax(p,100),lvl120:countMax(p,120),bond:bond10(p)}}
function renderCompare(){
 $('#compareTop').innerHTML=PLAYERS.map(p=>{const s=compareStats(p);const master=Math.max(1,state.roster.filter(r=>isCounted(r)&&isOwned(p,r)).length);const rate=Math.min(100,master/Math.max(1,state.roster.filter(isCounted).length)*100);return `<article class="master-card"><div class="head"><span class="name">${state.players[p]?.displayName||p}</span><span class="rank">MASTER</span></div><div class="big">${s.owned}</div><div class="sub">SERVANTS POSSEDES</div><div class="mini"><div class="cell"><small>5★</small><strong>${s.five}</strong></div><div class="cell"><small>4★</small><strong>${s.four}</strong></div><div class="cell"><small>WELFARE</small><strong>${s.wf}</strong></div><div class="cell"><small>SKILL 1</small><strong>${s.a1.toFixed(1)}</strong></div><div class="cell"><small>SKILL 2</small><strong>${s.a2.toFixed(1)}</strong></div><div class="cell"><small>SKILL 3</small><strong>${s.a3.toFixed(1)}</strong></div></div><div class="progress-line"><i style="width:${rate.toFixed(1)}%"></i></div></article>`}).join('');
 if(!compareFocusId){compareFocusId=state.roster.find(r=>isCounted(r)&&isOwned(currentPlayer,r))?.id||state.roster.find(isCounted)?.id}renderShowdown();renderRadar();initCompareNames();
}
function renderShowdown(){const r=state.roster.find(x=>Number(x.id)===Number(compareFocusId));if(!r)return;$('#compareFocusTitle').textContent=r.name;$('#compareCards').innerHTML=PLAYERS.map(p=>{const s=stats(p,r.id);const own=isOwned(p,r);return `<article class="duel-card"><div class="duel-hero" id="duel-${p}-${r.id}"><div class="loader">LOADING</div><div class="duel-name">${state.players[p]?.displayName||p}</div></div><div class="duel-body"><div class="duel-stat"><span>Possession</span><strong>${own?'YES':'NO'}</strong></div><div class="duel-stat"><span>Niveau</span><strong>${s.level??'—'}</strong></div><div class="duel-stat"><span>NP</span><strong>${s.np??'—'}</strong></div><div class="duel-stat"><span>Bond</span><strong>${s.bond??'—'}</strong></div><div class="duel-stat"><span>ATK / HP</span><strong id="duelStats-${p}">—</strong></div><div class="skill-squares">${(s.skills||[]).map((v,i)=>`<div class="square">S${i+1}<br>${v??'—'}</div>`).join('')}</div></div></article>`}).join('');PLAYERS.forEach(async p=>{const d=await atlasDetail(r);const urls=collectImageUrls(d);const e=$(`#duel-${p}-${r.id}`);if(urls[0]){const img=new Image();img.src=urls[0];img.onload=()=>{e.innerHTML=`<img src="${urls[0]}" alt="">${e.querySelector('.duel-name')?.outerHTML||`<div class="duel-name">${state.players[p]?.displayName||p}</div>`}`}}const st=calcStats(d,r,stats(p,r.id));$(`#duelStats-${p}`).textContent=st.atk&&st.hp?`${st.atk.toLocaleString()} / ${st.hp.toLocaleString()}`:'—'})}
function renderRadar(){const vals=PLAYERS.map(p=>{const s=compareStats(p);return{s,[0]:s.owned,[1]:s.a1*10,[2]:s.a2*10,[3]:s.a3*10,[4]:Math.min(10,s.lvl120),[5]:Math.min(10,s.bond/5)}});const max=10,cx=210,cy=210,R=150;const points=i=>{const ang=-Math.PI/2+i*Math.PI*2/6;return `${cx+Math.cos(ang)*R},${cy+Math.sin(ang)*R}`};let svg=`<svg class="radar" viewBox="0 0 420 420"><g fill="none" stroke="#303640" stroke-width="1">`;for(let k=1;k<=5;k++){const rr=R*k/5;let pts='';for(let i=0;i<6;i++){const ang=-Math.PI/2+i*Math.PI*2/6;pts+=`${cx+Math.cos(ang)*rr},${cy+Math.sin(ang)*rr} `}svg+=`<polygon points="${pts}"/>`}for(let i=0;i<6;i++){const ang=-Math.PI/2+i*Math.PI*2/6;svg+=`<line x1="${cx}" y1="${cy}" x2="${cx+Math.cos(ang)*R}" y2="${cy+Math.sin(ang)*R}"/>`}svg+=`</g>`;const label=['COLLECTION','S1','S2','S3','LV120','BOND'];label.forEach((t,i)=>{const a=-Math.PI/2+i*Math.PI*2/6;svg+=`<text x="${cx+Math.cos(a)*(R+25)}" y="${cy+Math.sin(a)*(R+25)}" fill="#727b85" font-size="10" text-anchor="middle">${t}</text>`});const ptsBy=p=>{const s=compareStats(p);const vals=[Math.min(10,s.owned/Math.max(1,state.roster.filter(isCounted).length)*10),s.a1,s.a2,s.a3,Math.min(10,s.lvl120),Math.min(10,s.bond/10)];return vals.map((v,i)=>{const a=-Math.PI/2+i*Math.PI*2/6;const rr=R*(v/10);return `${cx+Math.cos(a)*rr},${cy+Math.sin(a)*rr}`}).join(' ')};PLAYERS.forEach((p,i)=>svg+=`<polygon points="${ptsBy(p)}" fill="none" stroke="${['#d0b56b','#cb6670','#6eb7c4'][i]}" stroke-width="2"/>`);svg+='</svg>';const legend=PLAYERS.map(p=>`<div class="leg"><span>${state.players[p]?.displayName}</span><b>Skill ${compareStats(p).a1.toFixed(1)} / ${compareStats(p).a2.toFixed(1)} / ${compareStats(p).a3.toFixed(1)}</b></div>`).join('');$('#compareRadar').innerHTML=`<div class="radar-wrap"><div>${svg}</div><div class="radar-legend">${legend}<div class="support-note">Le radar est volontairement relatif : il met en scène vos écarts plutôt que de prétendre à un score de puissance officiel.</div></div></div>`}
function renderSupports(){const p=currentPlayer;$('#supportMasterTabs').innerHTML=PLAYERS.map(x=>`<button class="${x===p?'active':''}" data-support-player="${x}">${state.players[x]?.displayName||x}</button>`).join('');$$('[data-support-player]').forEach(b=>b.onclick=()=>{currentPlayer=b.dataset.supportPlayer;renderAll()});const ss=supportState[p]||{friendId:'',lists:[]};$('#supportFriendId').value=ss.friendId||'';$('#rayshiftLink').href=ss.friendId?`https://rayshift.io/na/${ss.friendId.replace(/\s/g,'')}`:'https://rayshift.io/lookup';const names=state.roster.filter(r=>isCounted(r)).slice(0,10);const lists=(ss.lists?.length?ss.lists:defaultSupportLists(names));$('#supportLists').innerHTML=lists.map((l,li)=>`<article class="support-list"><div class="list-head"><h3>${l.name}</h3><span class="list-tag">${l.event?'EVENT':'NORMAL'}</span></div><div class="support-slots">${l.slots.map((s,i)=>{const r=state.roster.find(x=>Number(x.id)===Number(s.servantId));return `<div class="support-slot"><div class="slot-class">${classIcon(s.class||r?.class||'Saber')}</div><div class="slot-main"><b>${r?.name||s.servant||'Emplacement vide'}</b><small>${s.level?`Lv ${s.level}`:'—'} · ${s.np?`NP ${s.np}`:'NP —'}</small></div><div class="slot-ce">${s.ce||'CE —'}</div></div>`}).join('')}</div></article>`).join('')}
function defaultSupportLists(names){return Array.from({length:6},(_,i)=>({name:`${i<3?'Normal':'Event'} ${i%3+1}`,event:i>=3,slots:Array.from({length:10},(_,j)=>({class:CLASS_ORDER[j%CLASS_ORDER.length],servantId:names[j]?.id||null,level:null,np:null,ce:''}))}))}
async function openServant(id){const r=state.roster.find(x=>Number(x.id)===Number(id));if(!r)return;const s=stats(currentPlayer,id),d=await atlasDetail(r),urls=collectImageUrls(d),can=currentCanEdit();const st=calcStats(d,r,s)||{};let idx=0;let htmlModal=buildModal(r,s,d,urls,st,can,idx);$('#modal').innerHTML=htmlModal;$('#modalBackdrop').classList.add('open');
 const redraw=(newIdx)=>{idx=(newIdx+urls.length)%urls.length;const img=$('#detailArtImg');if(img&&urls[idx]){img.src=urls[idx];$('#artCounter').textContent=`${idx+1} / ${urls.length}`}};$('#artPrev').onclick=()=>redraw(idx-1);$('#artNext').onclick=()=>redraw(idx+1);redraw(0);
 if(can){$('#saveServant').onclick=async()=>{saveModalValues(id);closeModal();await saveCloudStat(id);renderAll();toast(`${r.name} enregistré`)};}
}
function buildModal(r,s,d,urls,st,can,idx){const cards=commandCards(d,r);const coin=coinEstimate(r,s);return `<div class="detail-top"><div class="detail-art"><img id="detailArtImg" src="${urls[0]||''}" alt="${r.name}"><div class="art-nav"><button id="artPrev">←</button><span class="art-counter" id="artCounter">${urls.length?`1 / ${urls.length}`:'NO ART'}</span><button id="artNext">→</button></div></div><div class="detail-head"><div class="detail-header-line"><div><span class="eyebrow">${classKey(r.class)} · ${isWelfare(r)?'WELFARE':rarityNum(normalizeRarity(r.rarity))+'★'}</span><h2>${r.name}</h2><div class="meta">${d?.gender||''} ${d?.attribute?`· ${d.attribute}`:''}</div></div><div class="detail-badges"><span class="badge gold">NP ${s.np??'—'}</span><span class="badge">${coin?`COINS ${coin.value}${coin.estimated?'*':''}`:'COINS —'}</span></div></div><div class="stat-cards"><div class="stat-card"><small>LEVEL</small><strong>${s.level??'—'}</strong></div><div class="stat-card"><small>ATK</small><strong>${st.atk?.toLocaleString()||'—'}</strong></div><div class="stat-card"><small>HP</small><strong>${st.hp?.toLocaleString()||'—'}</strong></div><div class="stat-card"><small>BOND</small><strong>${s.bond??'—'}</strong></div></div></div></div><div class="command-section"><div class="subpanel"><h3>COMMAND CARDS</h3><div class="cards-line">${cards.map((c,i)=>`<div class="command-card ${c}"><div class="cc-color">${c==='B'?'BUSTER':c==='A'?'ARTS':'QUICK'}</div><small>${i+1}</small></div>`).join('')}</div></div><div class="subpanel"><h3>NP & GRAILS</h3><div class="cards-line"><div class="command-card"><div class="cc-color" style="background:#6f4aa6">NP ${s.np??'—'}</div><small>INPUT</small></div><div class="command-card"><div class="cc-color" style="background:#3a3430">${grailCount(s)} ${grailSvg()}</div><small>GRAILS</small></div></div></div></div>${can?buildEditor(r,s):'<div class="edit-section"><span class="read-only">LECTURE SEULE — aucune zone de modification pour ce compte.</span></div>'}`}
function buildEditor(r,s){return `<div class="edit-section"><div class="level-section"><div class="level-box"><h4>SKILLS</h4><div class="square-grid">${(s.skills||[]).map((v,i)=>`<label class="level-square"><span>S${i+1}</span><input id="skill-${i}" type="number" min="0" max="10" value="${v??''}"></label>`).join('')}</div></div><div class="level-box"><h4>APPENDS</h4><div class="square-grid">${(s.appendSkills||[]).map((v,i)=>`<label class="level-square"><span>A${i+1}</span><input id="append-${i}" type="number" min="0" max="10" value="${v??''}"></label>`).join('')}</div></div></div><div class="edit-grid" style="margin-top:10px"><div class="field"><label>Niveau</label><input id="e-level" type="number" min="1" max="120" value="${s.level??''}"></div><div class="field"><label>NP (brut)</label><input id="e-np" type="number" min="0" value="${s.np??''}"></div><div class="field"><label>Bond</label><input id="e-bond" type="number" min="0" value="${s.bond??''}"></div><div class="field"><label>Graals</label><input id="e-grail" type="number" min="0" max="15" value="${s.grail??''}"></div><div class="field"><label>Fou HP</label><input id="e-fouhp" type="number" min="0" value="${s.fouHp??''}"></div><div class="field"><label>Fou ATK</label><input id="e-fouatk" type="number" min="0" value="${s.fouAtk??''}"></div><div class="field"><label>Coins</label><input id="e-coins" type="number" min="0" value="${s.servantCoins??''}"></div></div><div class="modal-foot"><span class="read-only">NP affiché sur la card ≤ 5 · valeur brute conservée</span><div class="modal-actions"><button class="button" id="modalCancel">Annuler</button><button class="button bright" id="saveServant">Enregistrer</button></div></div></div>`}
function saveModalValues(id){const s=stats(currentPlayer,id);s.level=num($('#e-level').value);s.np=num($('#e-np').value);s.bond=num($('#e-bond').value);s.grail=num($('#e-grail').value);s.fouHp=num($('#e-fouhp').value);s.fouAtk=num($('#e-fouatk').value);s.servantCoins=num($('#e-coins').value);s.skills=[0,1,2].map(i=>num($('#skill-'+i).value));s.appendSkills=[0,1,2,3,4].map(i=>num($('#append-'+i).value));saveLocal()}
function closeModal(){$('#modalBackdrop').classList.remove('open')}
async function saveCloudStat(id){if(!cloudEnabled||!cloud||!currentAuth||!currentAuth.canEdit||currentAuth.playerKey!==currentPlayer)return;const s=stats(currentPlayer,id);const body={player_key:currentPlayer,servant_id:Number(id),level:s.level,np:s.np,bond:s.bond,grail:s.grail,skills:s.skills,append_skills:s.appendSkills,servant_coins:s.servantCoins,fou_hp:s.fouHp,fou_atk:s.fouAtk,updated_at:new Date().toISOString()};const {error}=await cloud.from('chaldea_stats').upsert(body,{onConflict:'player_key,servant_id'});if(error)toast('Erreur cloud');else updateSync('Cloud synchronisé')}
async function loadCloud(){if(!cloudEnabled||!cloud||!session)return;try{const {data,error}=await cloud.from('chaldea_stats').select('*');if(error)throw error;for(const x of data||[]){state.players[x.player_key] ||= {displayName:x.player_key,stats:{}};state.players[x.player_key].stats[String(x.servant_id)]={level:x.level,np:x.np,bond:x.bond,grail:x.grail,fouHp:x.fou_hp,fouAtk:x.fou_atk,servantCoins:x.servant_coins,skills:x.skills||[null,null,null],appendSkills:x.append_skills||[null,null,null,null,null]}};saveLocal();renderAll()}catch{updateSync('Cloud indisponible',true)}}
async function setupCloud(){if(!CONFIG.supabaseUrl||!CONFIG.supabaseAnonKey||!window.supabase)return;cloud=window.supabase.createClient(CONFIG.supabaseUrl,CONFIG.supabaseAnonKey);cloudEnabled=true;const {data}=await cloud.auth.getSession();session=data.session||null;if(session){await resolveMembership();updateSync(currentAuth?.canEdit?'Cloud · éditeur':'Cloud · lecteur')}cloud.auth.onAuthStateChange(async(_e,s)=>{session=s;currentAuth=null;if(s){await resolveMembership();await loadCloud();updateSync(currentAuth?.canEdit?'Cloud · éditeur':'Cloud · lecteur')}else{updateSync('Mode local');updateEditVisibility()}})}
async function resolveMembership(){if(!cloud||!session)return;const {data}=await cloud.from('chaldea_members').select('auth_user_id,player_key,display_name,can_edit').eq('auth_user_id',session.user.id).maybeSingle();currentAuth=data?{playerKey:data.player_key,canEdit:!!data.can_edit}:null;PLAYERS.forEach(p=>{if(data?.player_key===p)state.players[p].displayName=data.display_name||state.players[p].displayName});updateEditVisibility()}
function loginUI(){const sessionNow=session;$('#modal').innerHTML=`<div style="padding:28px"><span class="eyebrow">CLOUD ACCESS</span><h2 style="font:700 28px 'Space Grotesk';margin:7px 0 0">${sessionNow?'Compte connecté':'Connexion'}</h2><p style="color:#737d88;font-size:11px;line-height:1.6">${sessionNow?`${sessionNow.user.email}<br>${currentAuth?.canEdit?'Vous pouvez modifier votre propre roster.':'Compte en lecture seule.'}`:'Les trois Masters utilisent chacun leur compte Supabase. La lecture est commune ; l’écriture est limitée à son propre profil.'}</p>${sessionNow?`<div class="modal-actions" style="margin-top:20px"><button class="button" id="modalCancel">Fermer</button><button class="button danger" id="logout">Se déconnecter</button></div>`:`<div class="edit-grid" style="margin-top:18px"><div class="field"><label>Email</label><input id="loginEmail" type="email"></div><div class="field"><label>Mot de passe</label><input id="loginPassword" type="password"></div></div><div class="modal-actions" style="margin-top:16px"><button class="button" id="modalCancel">Annuler</button><button class="button bright" id="login">Se connecter</button></div>`}</div>`;$('#modalBackdrop').classList.add('open');$('#modalCancel').onclick=closeModal;if(sessionNow){$('#logout').onclick=async()=>{await cloud.auth.signOut();closeModal()}}else{$('#login').onclick=async()=>{const {error}=await cloud.auth.signInWithPassword({email:$('#loginEmail').value,password:$('#loginPassword').value});if(error)toast(error.message);else closeModal()}}}
function navigate(view){currentView=view;$$('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+view));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#pageName').textContent={overview:'Overview',servants:'Servants',compare:'Compare',supports:'Support Lists'}[view]||view;$('#sidebar').classList.remove('open');if(view==='overview')renderOverview();if(view==='servants')renderRoster();if(view==='compare')renderCompare();if(view==='supports')renderSupports()}
function renderAll(){renderMasterSwitch();renderOverview();if(currentView==='servants')renderRoster();if(currentView==='compare')renderCompare();if(currentView==='supports')renderSupports();updateEditVisibility()}
function saveLocal(){localStorage.setItem('chaldea-v4-state',JSON.stringify(state))}
function loadLocal(){try{const x=JSON.parse(localStorage.getItem('chaldea-v4-state'));if(x?.players){for(const p of PLAYERS){if(x.players[p])state.players[p]=x.players[p]}}}catch{}}
loadLocal();cleanState();fillFilters();renderAll();
function cleanState(){PLAYERS.forEach(p=>{state.players[p] ||= {displayName:p,stats:{}};Object.values(state.players[p].stats||{}).forEach(s=>{s.skills=Array.isArray(s.skills)?s.skills.slice(0,3):[null,null,null];s.appendSkills=Array.isArray(s.appendSkills)?s.appendSkills.slice(0,5):[null,null,null,null,null]})})}
$$('.nav-item').forEach(b=>b.onclick=()=>navigate(b.dataset.view));$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');$('#accountBtn').onclick=loginUI;$('#editRosterBtn').onclick=()=>navigate('servants');$('#modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()};$('#searchInput').oninput=renderRoster;$('#sortFilter').onchange=renderRoster;$('#sortDir').onclick=()=>{sortDir=sortDir==='desc'?'asc':'desc';$('#sortDir').textContent=sortDir==='asc'?'↑ Ascendant':'↓ Descendant';renderRoster()};$$('[data-roster-mode]').forEach(b=>b.onclick=()=>{rosterMode=b.dataset.rosterMode;$$('[data-roster-mode]').forEach(x=>x.classList.toggle('active',x===b));renderRoster()});$$('[data-pop]').forEach(b=>b.onclick=e=>{$$('.filter-pop.open').forEach(x=>x.classList.remove('open'));$('#'+b.dataset.pop).classList.toggle('open');e.stopPropagation()});document.addEventListener('click',closePops);$('#saveFriendId').onclick=()=>{supportState[currentPlayer].friendId=$('#supportFriendId').value.trim();renderSupports();toast('Friend ID enregistré')};$('#compareSearch').oninput=e=>{clearTimeout(compareSearchTimer);const q=norm(e.target.value);compareSearchTimer=setTimeout(()=>{const exact=state.roster.find(r=>norm(r.name)===q);const close=exact||state.roster.find(r=>norm(r.name).includes(q));if(close){compareFocusId=close.id;renderShowdown()}},120)};
setupCloud();syncRosterNA();
